### PR TITLE
Update mixins.less (solve #262)

### PR DESCRIPTION
**Pull request by JTS-IL**
Simple fix for issue #262
A thorough fix will take much longer.
if a small release is planned soon - please merge it and deploy

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
Hello JTS,
sorry haven't noticed was on my fork. Did you wanted to submit this to Nikeo's one?

**Comment by JTS-IL** [comment]
Hi Rocco,

I'm still learning how to use GitHub so I make some mistakes on the way...
Yes, I meant to submit this PR on the main Customizr fork, so can you help
me submitting this one on the correct fork?

10X

יעקב גלזר
-----------------------------------------------
בקרו באתר שלי : www.glezer.co.il

**Comment by eri-trabiccolo** [comment]
Hello JTS,
well you should go here -> https://github.com/Nikeo/customizr
and open a new pull-request there ;)

**Comment by JTS-IL** [comment]
OK
I hove I've done it right this time :-)

יעקב גלזר
-----------------------------------------------
בקרו באתר שלי : www.glezer.co.il

**Comment by eri-trabiccolo** [comment]
I think so :) Also you did it right all the other times ;)
Think that one time I opened a pull-request on my own repo :D

**Pull request closed without merging**
